<?php

/**
 * @file
 * Contains shorten_url_lite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shorten_url_lite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shorten_url_lite module.
    case 'help.page.shorten_url_lite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A lite weight url shortening service for your domain') . '</p>';
      return $output;

    default:
  }
}
